### ISSUE TITLE
Any recommendations on how to output the error pages as well?

### ISSUE THREAD

**Issue by etiennenoel** [norberttech/static-content-generator-bundle#179]
I'm using this using S3 + CloudFront and I really enjoy it. There's a way for S3 to redirect to a specific 404 page when a page doesn't exist and I have a template in my Symfony project at:

`templates/bundles/TwigBundle/Exception/error404.html.twig`

However, this doesn't get output in the `output` folder.

**Comment by norberttech** [comment]
I'm happy you enjoy this bundle! The reason it's not rendering error pages is because of this [filter](https://github.com/norberttech/static-content-generator-bundle/blob/1.x/src/NorbertTech/StaticContentGeneratorBundle/Command/GenerateRoutesCommand.php#L71). 
This bundle is generating static content for defined routes (except those that start with an underscore), and technically speaking `templates/bundles/TwigBundle/Exception/error404.html.twig` is not a route by itself. 

Probably the easiest way to render error pages would be to actually define them as a valid routes, something like: 

```
/**
 * @Route("/error_404", name="error_404")
 */
``` 

Will this solve your problem?

**Comment by norberttech** [comment]
I'm closing this one for now. If proposed solution will not work in your case, please provide more details about how would you like it to work.

**Comment by etiennenoel** [comment]
It works, thank you very much!

**Comment by norberttech** [comment]
🙌
